### ISSUE TITLE
Secure & HTTP Only cookie

### ISSUE THREAD

**Issue by mischabraam** [squeezely/magento2-plugin#30] opened 2022-11-23 08:53 UTC
On https://github.com/squeezely/magento2-plugin/blob/f3c56b8d767a5d59a4eda30aa9503865ae953fd9/Observer/LayoutLoadBefore.php#L85 a cookie named "sqzllocal" is set. It is not set secure or httponly, which means it's a security risc.

See https://magento.stackexchange.com/questions/227709/magento-2-how-to-set-secure-cookie-or-http-only-flag-set for information on how to fix this.

**Comment by Marvin-Magmodules** [comment] 2022-11-28 09:26
Hi @mischabraam thank you for opening this issue! Was not able to reproduce this issue, but the commit should force it to always use secure cookie for `sqzllocal`. Can you double check if this fixes the issue on your side?

**Comment by mischabraam** [comment] 2022-11-28 14:33
Seems to work. Thanks

**Comment by Marvin-Magmodules** [comment] 2022-11-28 18:54
Hi @mischabraam, thank you for checking this! Commit has been merged into release v2.8.1

**Closed as completed by Marvin-Magmodules** 2022-11-28 18:54 UTC
